### ISSUE TITLE
Create order attributes when converting an aborted order to a finalized order

### ISSUE THREAD

**Issue by andrewisplinghoff** [VIISON/shopware#11]
When converting an aborted order to a finalized order in the Shopware Backend by clicking on the "In reguläre Bestellung umwandeln" icon in the Marketing > Auswertungen > Abbruch-Analyse dialog, the order attributes are currently not created (no row is inserted into the database). This is problematic for the PickwareConnector, since at least in some cases this leads to not being able to pick the order (e.g. order no 1147629 in the Eisenschmidt test system).

We should probably fix this directly in Shopware and create a PR.

**Comment by samuelvogel** [comment]
Yes, this was the problem. The PAYONE Plugin actually has workaround always using a special function when accessing order attributes which checks first if they are actually present and creates them if not before returning them. Just FYI, not that we should do the same, we should fix it in Shopware.

Including @svenmuennich & @stefanheppenheimer so they stay informed.

**Comment by samuelvogel** [comment]
PR created: https://github.com/shopware/shopware/pull/656
