### ISSUE TITLE
No error message when document creation fails

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware#5]
Typical error, where the document model in the database is updated with the new date, but the PDF is not actually generated:

```
<B>mPDF error: </B>Unable to create output file: /www/files/documents/2971946d8b3adfb54c691a1c6f104eea.pdf
```

**Comment by andrewisplinghoff** [comment]
I assume this should become a PR?

**Comment by samuelvogel** [comment]
Yes, like all things we collect here.

**Comment by samuelvogel** [comment]
PR was created: https://github.com/shopware/shopware/pull/1250
