### ISSUE TITLE
Use new branch names from upstream shopware repository

### ISSUE THREAD

**Issue by flokli** [VIISON/shopware#8]
Shopwares branches are now called `4.3`, `5.0` and `5.1`, the repository itself is called `shopware` (without `-4`).

I'd suggest to apply this naming for our repository as well. Branches that were created for pull requests which are already merged could also be removed from here.

**Comment by samuelvogel** [comment]
Yes you are correct, we are out of sync with the changes made during the Shopware 5 release. We should align and clean up our branches!

**Comment by samuelvogel** [comment]
Please do that together with @andrewisplinghoff and @svenmuennich!

**Comment by samuelvogel** [comment]
The repository was renamed and the master branch is `5.1` at least, so I think this can be closed!
